# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-boardless.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path

path = str(Path.cwd())


class Ui_MainPage(object):

    #=================================Designer codes====================================
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 580)
        MainWindow.setStyleSheet("background-color: #E4E4E4; border-radius: 5px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 140, 580))
        self.sidebar.setStyleSheet("background-color: rgba(120, 91, 151, 0.8);")
        self.sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar.setObjectName("sidebar")
        self.btn_workspace = QtWidgets.QPushButton(self.sidebar)
        self.btn_workspace.setGeometry(QtCore.QRect(0, 50, 140, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_workspace.setFont(font)
        self.btn_workspace.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_workspace.setStyleSheet("QPushButton{\n"
"    background: none;\n"
"    color: #030613;\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(120, 91, 151, 0.9);\n"
"}")
        self.btn_workspace.setObjectName("btn_workspace")
        self.btn_help = QtWidgets.QPushButton(self.sidebar)
        self.btn_help.setGeometry(QtCore.QRect(0, 100, 140, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_help.setFont(font)
        self.btn_help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_help.setStyleSheet("QPushButton{\n"
"    background: none;\n"
"    color: #030613;\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(120, 91, 151, 0.9);\n"
"}")
        self.btn_help.setObjectName("btn_help")
        self.btn_about = QtWidgets.QPushButton(self.sidebar)
        self.btn_about.setGeometry(QtCore.QRect(0, 150, 140, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_about.setFont(font)
        self.btn_about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_about.setStyleSheet("QPushButton{\n"
"    background: none;\n"
"    color: #030613;\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(120, 91, 151, 0.9);\n"
"}")
        self.btn_about.setObjectName("btn_about")
        self.sidebar_photo = QtWidgets.QLabel(self.sidebar)
        self.sidebar_photo.setGeometry(QtCore.QRect(10, 390, 120, 120))
        self.sidebar_photo.setStyleSheet("background: none;")
        self.sidebar_photo.setText("")
        self.sidebar_photo.setPixmap(QtGui.QPixmap("%s/img/tasks.png" % path))
        self.sidebar_photo.setScaledContents(True)
        self.sidebar_photo.setObjectName("sidebar_photo")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(971, 10, 25, 25))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton{\n"
"background-color: #E4E4E4;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #d6d6d6;\n"
"}")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("%s/img/close.png" % path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(20, 20))
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minimize.setGeometry(QtCore.QRect(936, 10, 25, 25))
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"background-color: #E4E4E4;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #d6d6d6;\n"
"}")
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("%s/img/minimize.png" % path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setIconSize(QtCore.QSize(20, 20))
        self.btn_minimize.setObjectName("btn_minimize")
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setGeometry(QtCore.QRect(140, 10, 860, 570))
        self.pages.setObjectName("pages")
        self.page_workspace = QtWidgets.QWidget()
        self.page_workspace.setObjectName("page_workspace")
        self.frame = QtWidgets.QFrame(self.page_workspace)
        self.frame.setGeometry(QtCore.QRect(0, 0, 860, 110))
        self.frame.setStyleSheet("background-color: #C2C2C2; border-radius: 0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(240, 60, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background: none;")
        self.label_12.setObjectName("label_12")
        self.select_workspace = QtWidgets.QComboBox(self.frame)
        self.select_workspace.setGeometry(QtCore.QRect(370, 55, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.select_workspace.setFont(font)
        self.select_workspace.setStyleSheet("background-color: #E4E4E4;border-radius: 5px;")
        self.select_workspace.setObjectName("select_workspace")
        self.select_workspace.addItem("")
        self.btn_addworkspace = QtWidgets.QPushButton(self.frame)
        self.btn_addworkspace.setGeometry(QtCore.QRect(530, 55, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_addworkspace.setFont(font)
        self.btn_addworkspace.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addworkspace.setStyleSheet("border: 1px solid #030613; border-radius: 5px;")
        self.btn_addworkspace.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("%s/img/plus.png" % path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_addworkspace.setIcon(icon2)
        self.btn_addworkspace.setIconSize(QtCore.QSize(25, 25))
        self.btn_addworkspace.setObjectName("btn_addworkspace")
        self.frame_2 = QtWidgets.QFrame(self.page_workspace)
        self.frame_2.setGeometry(QtCore.QRect(0, 110, 860, 460))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pages.addWidget(self.page_workspace)
        self.page_help = QtWidgets.QWidget()
        self.page_help.setObjectName("page_help")
        self.label = QtWidgets.QLabel(self.page_help)
        self.label.setGeometry(QtCore.QRect(40, 95, 400, 61))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #030613;")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_help)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 400, 90))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #030613;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_help)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 400, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #030613;")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_help)
        self.label_4.setGeometry(QtCore.QRect(40, 310, 400, 71))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #030613;")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.btn_email = QtWidgets.QPushButton(self.page_help)
        self.btn_email.setGeometry(QtCore.QRect(40, 390, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_email.setFont(font)
        self.btn_email.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_email.setStyleSheet("background-color: #D55FAA; color: #030613;")
        self.btn_email.setObjectName("btn_email")
        self.label_5 = QtWidgets.QLabel(self.page_help)
        self.label_5.setGeometry(QtCore.QRect(40, 290, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #030613;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_help)
        self.label_6.setGeometry(QtCore.QRect(450, 80, 380, 380))
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("%s/img/help.png" % path))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pages.addWidget(self.page_help)
        self.page_about = QtWidgets.QWidget()
        self.page_about.setObjectName("page_about")
        self.label_7 = QtWidgets.QLabel(self.page_about)
        self.label_7.setGeometry(QtCore.QRect(410, 90, 440, 360))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("%s/img/todo.png" % path))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_about)
        self.label_8.setGeometry(QtCore.QRect(30, 125, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #030613;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_about)
        self.label_9.setGeometry(QtCore.QRect(30, 175, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #030613;")
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_about)
        self.label_10.setGeometry(QtCore.QRect(30, 240, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #030613;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page_about)
        self.label_11.setGeometry(QtCore.QRect(30, 290, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #030613;")
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.btn_github = QtWidgets.QPushButton(self.page_about)
        self.btn_github.setGeometry(QtCore.QRect(30, 350, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_github.setFont(font)
        self.btn_github.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_github.setStyleSheet("background-color: #D55FAA; color: #030613;")
        self.btn_github.setObjectName("btn_github")
        self.btn_socialmedia = QtWidgets.QPushButton(self.page_about)
        self.btn_socialmedia.setGeometry(QtCore.QRect(180, 350, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_socialmedia.setFont(font)
        self.btn_socialmedia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_socialmedia.setStyleSheet("background-color: #D55FAA; color: #030613;")
        self.btn_socialmedia.setObjectName("btn_socialmedia")
        self.pages.addWidget(self.page_about)
        self.sidebar.raise_()
        self.pages.raise_()
        self.btn_minimize.raise_()
        self.btn_close.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        self.btn_close.clicked.connect(MainWindow.close)
        self.btn_minimize.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.filling = QtWidgets.QFrame(MainWindow)
        self.filling.setGeometry(140,-6,860,16)
        self.filling.setStyleSheet('background-color: #C2C2C2; border-radius: 0px;')

        #==========================My codes===========================================
        self.btn_close.setStyleSheet('QPushButton{background-color: #C2C2C2;border-radius: 3px;}QPushButton:hover{background-color: #d6d6d6;}')
        self.btn_minimize.setStyleSheet('QPushButton{background-color: #C2C2C2;border-radius: 3px;}QPushButton:hover{background-color: #d6d6d6;}')
        self.btn_workspace.setStyleSheet('background-color: rgba(120, 91, 151, 0.9); color: #030613; border-radius: 0px;')

        self.btn_workspace.clicked.connect(lambda: [
                self.pages.setCurrentWidget(self.page_workspace),
                self.btn_workspace.setStyleSheet('background-color: rgba(120, 91, 151, 0.9); color: #030613; border-radius: 0px;'),
                self.btn_about.setStyleSheet('QPushButton{	background: none;	color: #030613;	border-radius: 0px;}QPushButton:hover{	background-color: rgba(120, 91, 151, 0.9);}'),
                self.btn_help.setStyleSheet('QPushButton{	background: none;	color: #030613;	border-radius: 0px;}QPushButton:hover{	background-color: rgba(120, 91, 151, 0.9);}'),
                self.filling.show(),
                self.btn_close.setStyleSheet('QPushButton{background-color: #C2C2C2;border-radius: 3px;}QPushButton:hover{background-color: #d6d6d6;}'),
        self.btn_minimize.setStyleSheet('QPushButton{background-color: #C2C2C2;border-radius: 3px;}QPushButton:hover{background-color: #d6d6d6;}')
                
        ])

        self.btn_about.clicked.connect(lambda: [
                self.pages.setCurrentWidget(self.page_about),
                self.btn_about.setStyleSheet('background-color: rgba(120, 91, 151, 0.9); color: #030613; border-radius: 0px;'),
                self.btn_workspace.setStyleSheet('QPushButton{	background: none;	color: #030613;	border-radius: 0px;}QPushButton:hover{	background-color: rgba(120, 91, 151, 0.9);}'),
                self.btn_help.setStyleSheet('QPushButton{	background: none;	color: #030613;	border-radius: 0px;}QPushButton:hover{	background-color: rgba(120, 91, 151, 0.9);}'),
                self.filling.hide(),
                self.btn_close.setStyleSheet('QPushButton{background-color: #E4E4E4;border-radius: 3px;}QPushButton:hover{background-color: #d6d6d6;}'),
                self.btn_minimize.setStyleSheet('QPushButton{background-color: #E4E4E4;border-radius: 3px;}QPushButton:hover{background-color: #d6d6d6;}')
        ])

        self.btn_help.clicked.connect(lambda: [
                self.pages.setCurrentWidget(self.page_help),
                self.btn_help.setStyleSheet('background-color: rgba(120, 91, 151, 0.9); color: #030613; border-radius: 0px;'),
                self.btn_about.setStyleSheet('QPushButton{	background: none;	color: #030613;	border-radius: 0px;}QPushButton:hover{	background-color: rgba(120, 91, 151, 0.9);}'),
                self.btn_workspace.setStyleSheet('QPushButton{	background: none;	color: #030613;	border-radius: 0px;}QPushButton:hover{	background-color: rgba(120, 91, 151, 0.9);}'),
                self.filling.hide(),
                self.btn_close.setStyleSheet('QPushButton{background-color: #E4E4E4;border-radius: 3px;}QPushButton:hover{background-color: #d6d6d6;}'),
                self.btn_minimize.setStyleSheet('QPushButton{background-color: #E4E4E4;border-radius: 3px;}QPushButton:hover{background-color: #d6d6d6;}')
        ])






    #------------------------------Designer codes
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_workspace.setText(_translate("MainWindow", "WorkSpaces"))
        self.btn_help.setText(_translate("MainWindow", "Help"))
        self.btn_about.setText(_translate("MainWindow", "About"))
        self.label_12.setText(_translate("MainWindow", "WorkSpace:"))
        self.select_workspace.setItemText(0, _translate("MainWindow", "test"))
        self.label.setText(_translate("MainWindow", "Create your own workspace , mange your activities and do them in the best way and time."))
        self.label_2.setText(_translate("MainWindow", "How to work with this app"))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "You can create many workspaces in \"WorkSpace\" part. Also, you can have many Boards in each workspace for different topickes."))
        self.label_4.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Ask your questions and report problems about this app using below link."))
        self.btn_email.setText(_translate("MainWindow", "Email"))
        self.label_5.setText(_translate("MainWindow", "Report problem"))
        self.label_8.setText(_translate("MainWindow", "About App"))
        self.label_9.setToolTip(_translate("MainWindow", "<html><head/><body><p>You can create many workspaces in &quot;WorkSpace&quot; part. Also, you can have many Boards in each workspace for different topickes.</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "This app help you manage your activities as well as posible"))
        self.label_10.setText(_translate("MainWindow", "About Creater"))
        self.label_11.setToolTip(_translate("MainWindow", "<html><head/><body><p>You can create many workspaces in &quot;WorkSpace&quot; part. Also, you can have many Boards in each workspace for different topickes.</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "A teenager who is intrested in programming.\nYou can support him using below links."))
        self.btn_github.setText(_translate("MainWindow", "GitHub"))
        self.btn_socialmedia.setText(_translate("MainWindow", "Social Media"))


    #-----------------------------My Functions--------------------------------------
