# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path

path = str(Path.cwd())


class Ui_TasksWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 580)
        MainWindow.setStyleSheet("background-color: #E4E4E4; border-radius: 5px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(965, 10, 25, 25))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton{\n"
"background-color: #E4E4E4;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #d6d6d6;\n"
"}")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("%s/img/close.png" % path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(20, 20))
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minimize.setGeometry(QtCore.QRect(930, 10, 25, 25))
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"background-color: #E4E4E4;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #d6d6d6;\n"
"}")
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("%s/img/minimize.png" % path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setIconSize(QtCore.QSize(20, 20))
        self.btn_minimize.setObjectName("btn_minimize")
        self.btn_backpage = QtWidgets.QPushButton(self.centralwidget)
        self.btn_backpage.setGeometry(QtCore.QRect(10, 10, 25, 25))
        self.btn_backpage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_backpage.setStyleSheet("QPushButton{\n"
"background-color: #E4E4E4;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #d6d6d6;\n"
"}")
        self.btn_backpage.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("%s/img/back-arrow.png" % path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_backpage.setIcon(icon2)
        self.btn_backpage.setIconSize(QtCore.QSize(20, 20))
        self.btn_backpage.setObjectName("btn_backpage")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(380, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("background: none;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 50, 1000, 530))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1000, 530))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1000, 530))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.horizontalScrollBar().setEnabled(False)
        # self.task_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.task_frame.sizePolicy().hasHeightForWidth())
        # self.task_frame.setSizePolicy(sizePolicy)
        # self.task_frame.setMinimumSize(QtCore.QSize(970, 50))
        # self.task_frame.setStyleSheet("background-color:  rgba(120, 91, 151, 0.8);")
        # self.task_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.task_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.task_frame.setObjectName("task_frame")
        # self.task_name = QtWidgets.QLabel(self.task_frame)
        # self.task_name.setGeometry(QtCore.QRect(10, 0, 830, 50))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(9)
        # self.task_name.setFont(font)
        # self.task_name.setStyleSheet("background: none;")
        # self.task_name.setAlignment(QtCore.Qt.AlignCenter)
        # self.task_name.setObjectName("task_name")
        # self.task_delete = QtWidgets.QPushButton(self.task_frame)
        # self.task_delete.setGeometry(QtCore.QRect(910, 10, 50, 30))
        # self.task_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        # self.task_delete.setStyleSheet("background-color: #D55FAA;")
        # self.task_delete.setText("")
        # icon3 = QtGui.QIcon()
        # icon3.addPixmap(QtGui.QPixmap("%s/img/delete.png" % path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.task_delete.setIcon(icon3)
        # self.task_delete.setIconSize(QtCore.QSize(20, 20))
        # self.task_delete.setObjectName("task_delete")
        self.task_done = QtWidgets.QPushButton(MainWindow)
        self.task_done.hide()
        # self.task_done.setGeometry(QtCore.QRect(850, 10, 50, 30))
        # self.task_done.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        # self.task_done.setStyleSheet("background-color: #D55FAA;")
        # self.task_done.setText("")
        # icon4 = QtGui.QIcon()
        # icon4.addPixmap(QtGui.QPixmap("%s/img/check.png" % path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.task_done.setIcon(icon4)
        # self.task_done.setIconSize(QtCore.QSize(20, 20))
        # self.task_done.setObjectName("task_done")
        # self.verticalLayout.addWidget(self.task_frame)
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btn_addtask = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addtask.setGeometry(QtCore.QRect(60, 8, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btn_addtask.setFont(font)
        self.btn_addtask.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addtask.setStyleSheet("border: 1px solid #030613; color: #030613;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("%s/img/plus.png" % path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_addtask.setIcon(icon5)
        self.btn_addtask.setObjectName("btn_addtask")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_close.clicked.connect(MainWindow.close)
        self.btn_minimize.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Tasks"))
        # self.task_name.setText(_translate("MainWindow", "Learning Python"))
        self.btn_addtask.setText(_translate("MainWindow", "Add Task"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_TasksWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
